"""
Step 2: Product Image Generation
Takes the product concept generated by Ozzy's build_prompt()
and generates a product image using Hugging Face FLUX.
"""

import os
from dotenv import load_dotenv
from huggingface_hub import InferenceClient

from input.input_build_prompt import build_prompt

load_dotenv()

IMAGE_MODEL = "black-forest-labs/FLUX.1-schnell"

_client = None


def _get_client():
    """
    Lazily creates the HF client on first use, instead of at
    import time. This means importing this module elsewhere
    (e.g. Ozzy's UI) won't crash the whole app if HF_TOKEN
    isn't set — the error only surfaces when an image is
    actually requested.
    """
    global _client

    if _client is None:
        token = os.environ.get("HF_TOKEN")

        if not token:
            raise ValueError(
                "HF_TOKEN is not set. Add it to your .env file."
            )

        _client = InferenceClient(
            provider="hf-inference",
            api_key=token,
        )

    return _client


def generate_image(
    product_description,
    industry=None,
    target_audience=None,
    page_theme=None,
    layout_style=None,
    spacing=None,
    tone=None,
    color_scheme=None,
    extra_notes=None,
    product_files=None,
    theme_files=None,
    output_path="product_image.png"
):
    """
    1. Calls build_prompt() to generate the product concept.
    2. Converts that concept into an image generation prompt.
    3. Sends it to Hugging Face FLUX.
    4. Saves the generated image.
    """

    # Step 1: Get product concept from Ozzy's build_prompt
    product_concept, error = build_prompt(
        product_description=product_description,
        industry=industry,
        target_audience=target_audience,
        page_theme=page_theme,
        layout_style=layout_style,
        spacing=spacing,
        tone=tone,
        color_scheme=color_scheme,
        extra_notes=extra_notes,
        product_files=product_files,
        theme_files=theme_files,
    )

    if error:
        raise ValueError(error)


    # Step 2: Convert product concept into an image-focused prompt
    image_prompt = f"""
Create a professional product image based on this product concept:

{product_concept}

Requirements:
- photorealistic product photography
- premium commercial style
- clean studio background
- realistic lighting and shadows
- detailed materials and textures
- visually appealing composition
- no text
- no logos
- no people
"""


    # Step 3: Generate image using Hugging Face
    image = _get_client().text_to_image(
        prompt=image_prompt,
        model=IMAGE_MODEL,
    )


    # Step 4: Save image
    image.save(output_path)

    return output_path



if __name__ == "__main__":

    image_path = generate_image(
        product_description=(
            "A sleek smart water bottle with a small LED hydration display "
            "and temperature tracking."
        ),
        industry="Consumer Electronics",
        target_audience="Fitness enthusiasts and professionals",
        page_theme="Modern Minimalist",
        layout_style="Clean product showcase",
        spacing="Balanced",
        tone="Professional",
        color_scheme="Matte navy and silver",
        extra_notes=(
            "Studio product photography with a white background "
            "and soft shadows."
        )
    )

    print(f"Image saved at: {image_path}")
